#!/usr/bin/env ruby
oldrev, newrev = ARGV
$stdout.sync = true

def system_with_log command
  puts "Running command: #{command}"
  system command
end

class Array
  # scans the list of files to see if any of them are under the given path
  def any_in_dir?(dir)
    if Array === dir
      exp = %r{^(?:#{dir.join('|')})/}
      any? { |file| file =~ exp }
    else
      dir += '/'
      any? { |file| file.index(dir) == 0 }
    end
  end
end

puts "Upgrading from #{oldrev} to #{newrev}"

# get a list of files that changed
changes = `git diff #{oldrev} #{newrev} --diff-filter=ACDMR --name-status`.split("\n")

# make a hash of files that changed and how they changed
changes_hash = changes.inject(Hash.new { |h, k| h[k] = [] }) do |hash, line|
  modifier, filename = line.split("\t", 2)
  hash[modifier] << filename
  hash
end

# create an array of files added, copied, modified or renamed
modified_files = %w(A C M R).inject([]) { |files, bit| files.concat changes_hash[bit] }
added_files = changes_hash['A'] # added
deleted_files = changes_hash['D'] # deleted
changed_files = modified_files + deleted_files # all
puts "files changed: #{changed_files.size}"

if changed_files.include?('Gemfile') || changed_files.include?('Gemfile.lock')
  # update bundled gems if manifest file has changed
  system_with_log %(bash -lc 'umask 002 && . .rvmrc && bundle install')
end

#if changed_files.include?('config/schedule.rb')
  ## update crontab if whenever schedule has changed
  #system_with_log %(bash -lc 'umask 002 && . .rvmrc && bundle exec whenever --update-crontab')
#end

#run migrations when new ones added
if new_migrations = added_files.any_in_dir?('db/migrate')
  system_with_log %(bash -lc 'umask 002 && . .rvmrc && RACK_ENV=production bundle exec rake db:migrate')
end

# Restart the THIN webserver
dirname = File.basename(Dir.getwd)
system_with_log %(bash -lc 'sudo /etc/init.d/#{dirname} restart')
